[package]
name = "clap-fundsp"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
fundsp = "0.20.0"
parking_lot = "0.12"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git" }
